import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import CartProvider from './components/Providers'
import ShoppingCartModal from './components/ShoppingCartModal'
import { Facebook, Instagram, Mail, Youtube } from 'lucide-react'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <title>Home Page</title>
      <body className={inter.className}>
        <CartProvider>
          <Navbar />
          <ShoppingCartModal/>
          <div className='pb-8'>
            {children}
          </div>

          <div className='pt-4 border-t border-gray-200'>
            <div className='flex justify-center items-center sm:px-6 text-gray-500 pb-4 gap-4 cursor-pointer'>
              <Facebook size={20} />
              <Youtube size={22}/>
              <Instagram size={18} />
              <div className='flex justify-center items-center border-l-2 pl-4'>
                <Mail size={20} /> <span className='text-sm'>Email: nht1072@gmail.com</span> 
              </div>
            </div>
            <footer className='flex justify-center items-center px-4 pb-4 sm:px-6 text-gray-500'>
              ©️ TK2 - All rights reserved
            </footer>
          </div>
        </CartProvider>
      </body>
      </html>
    </ClerkProvider>
      
  )
}
